CREATE TABLE LIM_USER(
	USER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_ID VARCHAR2(20) UNIQUE NOT NULL,
	USER_PWD VARCHAR2(100) NOT NULL,
	USER_NAME NVARCHAR2(20) NOT NULL,
	ROLE VARCHAR2(20) NOT NULL,
	STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE NOT NULL
)


