CREATE TABLE SEMI_COMMENT(
	COMMENT_NO NUMBER PRIMARY KEY,
	COMMENT_WRITER VARCHAR2(20) REFERENCES SEMI_MEMBER,
	REF_BOARD_NO NUMBER REFERENCES SEMI_BOARD,
	COMMENT_CONTENT NVARCHAR2(2000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	



)