DROP TABLE "RENTAL";

CREATE TABLE "RENTAL" (
	"RENTAL_NUMBER"	NVARCHAR2(10)		NOT NULL,
	"CUSTOMERS_NUMBER"	NVARCHAR2(9)		NOT NULL,
	"CABINET_NUMBER"	NVARCHAR2(4)		NOT NULL,
	"RENTAL_FEE"	NUMBER		NOT NULL,
	"RENTAL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

DROP TABLE "CUSTOMERS";

CREATE TABLE "CUSTOMERS" (
	"CUSTOMERS_NUMBER"	NVARCHAR2(9)		NOT NULL,
	"CUSTOMERS_ID"	NVARCHAR2(15)		NOT NULL,
	"PHONENUMBER"	NUMBER		NOT NULL
);

DROP TABLE "CABINET";

CREATE TABLE "CABINET" (
	"CABINET_NUMBER"	NVARCHAR2(4)		NOT NULL,
	"CABINET_SIZE"	CHAR(3)		NOT NULL
);

ALTER TABLE "RENTAL" ADD CONSTRAINT "PK_RENTAL" PRIMARY KEY (
	"RENTAL_NUMBER"
);

ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY (
	"CUSTOMERS_NUMBER"
);

ALTER TABLE "CABINET" ADD CONSTRAINT "PK_CABINET" PRIMARY KEY (
	"CABINET_NUMBER"
);

ALTER TABLE "RENTAL" ADD CONSTRAINT "UK_RENTAL_CABINET" 
    UNIQUE ("CABINET_NUMBER");

ALTER TABLE "CABINET" ADD CONSTRAINT "크기는 대 중 소만" CHECK (CABINET_SIZE IN ('대', '중', '소'));


SELECT * FROM CABINET;
SELECT * FROM RENTAL;
SELECT * FROM CUSTOMERS;

