CREATE TABLE TV_MEMBER(
	MEMBER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) UNIQUE NOT NULL,
	MEMBER_PWD VARCHAR2(100) NOT NULL,
	MEMBER_NAME NVARCHAR2(30) NOT NULL,
	ROLE VARCHAR2(20) NOT NULL,
	DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE NOT NULL
)

SELECT * FROM TV_MEMBER;
