CREATE TABLE ANNO_CATEGORY(
	CATEGORY_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CATEGORY_NAME NVARCHAR2(20) NOT NULL 
);

INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( '공지사항'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( '자유'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( '정보'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( '개그'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( 'PVP'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( 'RPG'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( '소울라이크'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( 'AOS'
);
INSERT INTO ANNO_CATEGORY (CATEGORY_NAME) VALUES ( 'FPS'
);

SELECT * FROM ANNO_CATEGORY;

CREATE TABLE ANNO_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BOARD_TITLE NVARCHAR2(200) NOT NULL,
	BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
	BOARD_COUNT NUMBER DEFAULT 0 NOT NULL,
	USER_ID VARCHAR2(30) NOT NULL,
	USER_PWD VARCHAR2(100) NOT NULL,
	CATEGORY_NO NUMBER REFERENCES ANNO_CATEGORY,
	DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')) NOT NULL,
	REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

// BOARD_TITLE, BOARD_CONTENT, USER_ID, USER_PWD, CATEGORY_NO 게시판 작성
// BOARD_NO, BOARD_TITLE, BOARD_COUNT, 랜덤한 아이디값, REG_DATE 게시판 목록 조회
// BOARD_NO, BOARD_TITLE, BOARD_COUNT, 랜덤한 아이디값, REG_DATE, BOARD_CONTENT 게시판 상세조회
// BOARD_NO, USER_ID, USER_PWD, BOARD_TITLE, BOARD_CONTENT 게시판 수정
// BOARD_NO, USER_ID, USER_PWD 게시판 삭제

SELECT * FROM ANNO_BOARD;
CREATE TABLE ANNO_COMMENT(
	COMMENT_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	COMMENT_CONTENT NVARCHAR2(200) NOT NULL,
	USER_ID VARCHAR2(30) NOT NULL,
	USER_PWD VARCHAR2(100) NOT NULL,
	BOARD_NO NUMBER NOT NULL REFERENCES ANNO_BOARD ON DELETE CASCADE,
	DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN('Y', 'N')) NOT NULL,
	REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)

SELECT * FROM ANNO_COMMENT;



