-- 멤버에 필요한 요소
-- 1. 유저 식별자 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
-- 2. 유저 아이디 VARCHAR2(30) UNIQUE NOT NULL
-- 3. 유저 비밀번호 VARCHAR2(15) NOT NULL
-- 4. 유저 닉네임 NVARCHAR2(20) NOT NULL
-- 5. 이메일 VARCHAR2(30) NOT NULL
-- 6. 가입일 DATE DEFAULT SYSDATE
-- 7. 정보 변경일 DATE DEFAULT SYSDATE
-- 8. 탈퇴 여부 CHAR(1) DEFAULT 'N' CHECK(STATUS IN('Y', 'N'))
CREATE TABLE H_MEMBER (
	USER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
	USER_ID VARCHAR2(30) UNIQUE NOT NULL,
	USER_PWD VARCHAR2(15) NOT NULL,
	USER_NAME NVARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	MODIFY_DATE DATE DEFAULT SYSDATE,
	STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN('Y', 'N'))
);

SELECT * FROM H_MEMBER;
DROP TABLE H_MEMBER;