SELECT * FROM DBA_USERS;
SELECT * FROM ANIMAL ORDER BY ANIMAL_ID DESC;

-- 진료기록 테이블 만들기
CREATE TABLE MEDICAL_RECORD (
	RECORD_ID CHAR(5),
	ANIMAL_NO CHAR(3),
	CHECK_DATE DATE,
	DOCTOR_NAME NVARCHAR2(21),
	TREATMENT NVARCHAR2(500)
);

SELECT * FROM MEDICAL_RECORD;

INSERT INTO MEDICAL_RECORD
VALUES ('R0001', 'A01', SYSDATE, '홍길동', '영양제투여');

INSERT INTO MEDICAL_RECORD
VALUES (NULL, NULL, SYSDATE, '고길동', '영양제투여');

INSERT INTO MEDICAL_RECORD
VALUES ('R0001', NULL, SYSDATE, '홍길동', '영양제투여');

INSERT INTO MEDICAL_RECORD
VALUES ('R0002', 'ABC', SYSDATE, '홍길동', '영양제투여');

---------------------------------------------------------------------------

DROP TABLE MEDICAL_RECORD;

SELECT * FROM MEDICAL_RECORD;

CREATE TABLE MEDICAL_RECORD(
	RECORD_ID CHAR(5) PRIMARY KEY,
	ANIMAL_ID CHAR(3) NOT NULL,
	CHECK_DATE DATE DEFAULT SYSDATE NOT NULL,
	SEVERITY CHAR(1),
	CONSTRAINT SEV_CK CHECK (SEVERITY IN('H', 'M', 'L')),
	FOREIGN KEY(ANIMAL_ID) REFERENCES ANIMAL(ANIMAL_ID)
);

INSERT INTO MEDICAL_RECORD
VALUES (NULL, NULL, NULL, NULL);

INSERT INTO MEDICAL_RECORD
VALUES ('R0001', NULL, NULL, NULL);

INSERT INTO MEDICAL_RECORD
VALUES ('R0001', 'A01', SYSDATE, 'M');

INSERT INTO MEDICAL_RECORD(RECORD_ID, ANIMAL_ID, SEVERITY)
VALUES ('R0002', 'A02', 'H');

INSERT INTO MEDICAL_RECORD
VALUES ('R0001', 'A91', SYSDATE, 'M');

SELECT
	RECORD_ID
     ,	ANIMAL_NAME
FROM
	MEDICAL_RECORD
JOIN
	ANIMAL USING(ANIMAL_ID);

SELECT * FROM MEDICAL_RECORD;

ALTER TABLE MEDICAL_RECORD ADD COST NUMBER;

ALTER TABLE MEDICAL_RECORD MODIFY RECORD_ID CHAR(6);

ALTER TABLE MEDICAL_RECORD RENAME COLUMN CHECK_DATE TO CK_DATE;

ALTER TABLE MEDICAL_RECORD DROP COLUMN COST;