SELECT * FROM ZONE; WHERE ZONE_ID = '1';

CREATE SEQUENCE SEQ_SPECIES
START WITH 13
NOCACHE;

CREATE SEQUENCE SEQ_KEEPER 
START WITH 10 
NOCACHE;


/* 회원 / 게시판
 * 회원파트 : C(회원가입) / R(로그인) / 로그아웃
 * 게시글 작성 조건 : 로그인 5회 이상
 * 게시판 : C(게시글작성) / R(목록조회) / R (상세조회)
 */

CREATE TABLE JDBC_MEMBER(
    MEMBER_ID VARCHAR2(30) PRIMARY KEY,
    MEMBER_PWD VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE JDBC_BOARD(
    BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY,
    BOARD_TITLE NVARCHAR2(2000) NOT NULL,
    BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
    BOARD_WRITER VARCHAR2(30) NOT NULL,
    FOREIGN KEY(BOARD_WRITER) REFERENCES JDBC_MEMBER
);

CREATE TABLE LOGIN_CHECK(
    LOGIN_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    MEMBER_ID VARCHAR2(30) NOT NULL,
    LOGIN_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY(MEMBER_ID) REFERENCES JDBC_MEMBER	
);

DROP TABLE JDBC_BOARD;

CREATE SEQUENCE JDBC_BOARD
START WITH 1
NOCACHE;


SELECT * 
FROM USER_SEQUENCES 
ORDER BY SEQUENCE_NAME;

		SELECT
			   ANIMAL_ID
			 , ANIMAL_NAME
			 , SPECIES_NAME
			 , ZONE_NAME
			 , KEEPER_NAME
			 , GENDER
			 , WEIGHT_KG
		  FROM
		  	   ANIMAL
		  JOIN
		  	   SPECIES USING(SPECIES_ID)
		  JOIN
		  	   ZONE USING(ZONE_ID)
		  JOIN 
		  	   KEEPER USING(KEEPER_ID)
		 ORDER
		 	BY
		 	   ANIMAL_ID DESC;
		
				SELECT
			   ANIMAL_ID animalId
			 , ANIMAL_NAME animalName
			 , SPECIES_NAME speciesId
			 , ZONE_NAME zoneId
			 , NVL(KEEPER_NAME, '미배정') keeperId
			 , GENDER gender
			 , WEIGHT_KG weightKg
		  FROM
		  	   ANIMAL
		  LEFT
		  JOIN
		   	   SPECIES USING(SPECIES_ID)
		  LEFT
		  JOIN
		  	   ZONE USING(ZONE_ID)
		  LEFT
		  JOIN 
		  	   KEEPER USING(KEEPER_ID)
		 WHERE
		 	   ANIMAL_ID = 'A37'; 	
				
		SELECT
				ANIMAL_ID
		     ,  ANIMAL_NAME
			 ,  SPECIES_ID
			 ,  ZONE_ID
			 ,  KEEPER_ID
		  FROM
		  		ANIMAL
		 WHERE
		 		ANIMAL_NAME LIKE '%이%';				

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				